#!/bin/bash

DOTFILES_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)
for file in $(find $DOTFILES_DIR -type f -name "*install.sh") ; do
  echo ""
  echo ""
  echo "----------------------------------------------------------------------"
  echo "RUNNING: $file"
  echo ""
  source $file
done
