#!/bin/bash

DOTFILES_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)
SYMLINK_FILES=$(find $DOTFILES_DIR -type f -name "*.symlink*")

set -e

for file in $SYMLINK_FILES; do
  dest="$HOME/.$(basename $file | sed 's/\.symlink\(.*\)$//')"
  echo "SYMLINKING $dest => $file"
  if [ -f $dest ] && [ ! -L $dest ] ; then
    mv $dest $dest.backup.$(date +"%F-%T")
    ln -s $file $dest
  fi
  if [ -L $dest ] ; then
    if [ "`readlink -f $dest`" != "$file" ] ; then
      mv $dest $dest.backup.$(date +"%F-%T")
      ln -s $file $dest
    fi
  else
    ln -s $file $dest
  fi
done
