
windowrule {
  name = windowrule-1
  workspace = name:OT
  match:class = ^(Todoist)$
}


windowrule {
  name = windowrule-2
  workspace = name:OT
  match:class = ^(obsidian)$
}


windowrule {
  name = windowrule-3
  workspace = name:Slack
  match:class = ^(Slack)$
}


# This does no longer work after omarchy changes to make 1password floating by default
# I think I actually prefer that over a default namespace.
# windowrule = workspace name:1Password, floating: 0, class:1password, initialTitle:1Password
# windowrule = size 1400 900, floating:0, class:1password
# windowrule = pseudo, floating:0, class:1password
# windowrule = center, floating:0, class:1password

windowrule {
  name = windowrule-4
  workspace = name:Spotify
  match:class = spotify
}

