install: ${HOME}/.gtkrc-2.0 ${HOME}/.gtk-3.0/

${HOME}/.gtkrc-2.0:
	rm -rf ${HOME}/.gtkrc-2.0
	ln -s ${PWD}/gtkrc-2.0 ${HOME}/.gtkrc-2.0

${HOME}/.gtk-3.0/:
	rm -rf ${HOME}/.gtk-3.0
	ln -s ${PWD}/gtk-3.0 ${HOME}/.gtk-3.0
